# Generated by Django 2.2 on 2019-08-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='song',
            name='audio',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
