# Generated by Django 2.2 on 2019-08-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20190819_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(blank=True, upload_to='audio/'),
        ),
    ]
