# Generated by Django 2.2 on 2019-09-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
