# Generated by Django 2.2 on 2019-09-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_song_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='url',
        ),
    ]
